version: '{build}'
skip_tags: true
image: Visual Studio 2022
configuration: Release
test: off
build_script:
- ps: ./Build.ps1
artifacts:
- path: artifacts/Destructurama.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: b3Ey7xZBqBMoBKScqgiO/cf4u93jKdx5h+/5qtwvpKrVRBfwp0fjjeCFAUO3Tepo
  skip_symbols: true
  on:
    branch: /^(master|dev)$/
