version: '{build}'
skip_tags: true
image: Visual Studio 2022
configuration: Release
test: off
build_script:
- ps: ./Build.ps1
artifacts:
- path: artifacts/Destructurama.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: 6khWtJKzfC7zUVqIs98f+Ag6hDONafPvvBje6rrI5aP05hjcxyeg3Ro6Upw4fvjo
  skip_symbols: true
  on:
    branch: /^(master|dev)$/
